# Generated by Django 5.1.7 on 2025-04-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0002_remove_resposta_texto_resposta_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='texto',
            field=models.CharField(default='Sem texto', max_length=255),
        ),
    ]
