# Generated by Django 5.1.7 on 2025-04-22 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0003_resposta_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='imagem',
            field=models.ImageField(blank=True, default='path/to/default/image.png', null=True, upload_to='respostas/'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='testes.pergunta'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='texto',
            field=models.TextField(),
        ),
    ]
