# Generated by Django 5.1.7 on 2025-04-22 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0005_resposta_explicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='explicacao',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='texto',
        ),
        migrations.AlterField(
            model_name='resposta',
            name='imagem',
            field=models.ImageField(default='images/default.jpg', upload_to='respostas/'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.pergunta'),
        ),
    ]
