# Generated by Django 5.1.7 on 2025-04-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0008_resultado_tempo_resultado_tentativas'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='mensagem_inicial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
