# Generated by Django 5.1.7 on 2025-04-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0009_teste_mensagem_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teste',
            name='perguntas_respondidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teste',
            name='total_perguntas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
