# Generated by Django 5.1.7 on 2025-04-26 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0010_teste_estado_teste_perguntas_respondidas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teste',
            name='estado',
        ),
        migrations.CreateModel(
            name='ResultadoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativas', models.IntegerField(default=1)),
                ('correta', models.BooleanField(default=False)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.pergunta')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.resultado')),
            ],
        ),
    ]
