# Generated by Django 5.1.7 on 2025-04-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0012_aula_remove_resposta_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_perguntas/'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
