# Generated by Django 5.1.7 on 2025-04-30 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0013_pergunta_tipo_pergunta_video_resposta_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='perguntas/'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_respostas/'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='respostas/'),
        ),
    ]
