# Generated by Django 5.1.7 on 2025-05-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0014_pergunta_imagem_resposta_video_alter_resposta_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='mensagem_inicial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
