# Generated by Django 5.1.7 on 2025-05-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0015_teste_mensagem_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='numero',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
