# Generated by Django 5.1.7 on 2025-05-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0017_delete_aula_resposta_aluno_alter_resultado_pontuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='aluno',
        ),
        migrations.AlterField(
            model_name='resultado',
            name='pontuacao',
            field=models.FloatField(default=0),
        ),
    ]
