# Generated by Django 5.1.7 on 2025-04-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_remove_aula_subtitulo_alter_aula_ordem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='descricao',
        ),
        migrations.AddField(
            model_name='aula',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='aulas_images/'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='aulas_images/'),
        ),
    ]
