# Generated by Django 5.1.7 on 2025-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='aulas/'),
        ),
    ]
