# Generated by Django 5.1.7 on 2025-04-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0007_aulaconcluida'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
