# Generated by Django 5.1.7 on 2025-04-30 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0008_aula_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='aulas.aula')),
            ],
        ),
    ]
