# Generated by Django 5.1.7 on 2025-04-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0009_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
