# Generated by Django 5.1.7 on 2025-05-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0010_video_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
