# Generated by Django 5.1.7 on 2025-05-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0011_imagem_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='palavras/')),
                ('video', models.FileField(blank=True, null=True, upload_to='palavras/videos/')),
            ],
        ),
        migrations.AlterField(
            model_name='imagem',
            name='descricao',
            field=models.TextField(),
        ),
    ]
