# Generated by Django 5.1.7 on 2025-05-02 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0002_palavra_imagem_palavra_nome_alter_palavra_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavra',
            name='texto',
        ),
        migrations.AlterField(
            model_name='palavra',
            name='imagem',
            field=models.ImageField(upload_to='palavras/'),
        ),
        migrations.AlterField(
            model_name='palavra',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='UtilizadorPalavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistida_em', models.DateTimeField(auto_now_add=True)),
                ('palavra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.palavra')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizador', 'palavra')},
            },
        ),
        migrations.AddField(
            model_name='palavra',
            name='utilizadores',
            field=models.ManyToManyField(related_name='palavras_desbloqueadas', through='pesquisa.UtilizadorPalavra', to=settings.AUTH_USER_MODEL),
        ),
    ]
