# Generated by Django 5.1.7 on 2025-05-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0006_alter_palavra_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palavra',
            old_name='palavra',
            new_name='texto',
        ),
        migrations.AddField(
            model_name='palavra',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_palavras/'),
        ),
        migrations.AddField(
            model_name='palavra',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
