# Generated by Django 5.1.7 on 2025-04-18 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='subtitulo',
        ),
        migrations.AlterField(
            model_name='aula',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aula',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='aulas/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='aulas.aula')),
            ],
        ),
    ]
