# Generated by Django 5.1.7 on 2025-04-19 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_remove_imagem_descricao_aula_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='imagem',
        ),
    ]
