# Generated by Django 5.1.7 on 2025-05-02 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0003_remove_palavra_texto_alter_palavra_imagem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavra',
            name='utilizadores',
        ),
        migrations.RemoveField(
            model_name='palavra',
            name='categoria',
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='palavra',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='palavras', to='pesquisa.aula'),
        ),
        migrations.CreateModel(
            name='UtilizadorAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistida_em', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa.aula')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizador', 'aula')},
            },
        ),
        migrations.DeleteModel(
            name='UtilizadorPalavra',
        ),
    ]
