# Generated by Django 5.1.7 on 2025-05-04 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0012_palavra_alter_imagem_descricao'),
        ('pesquisa', '0004_remove_palavra_utilizadores_remove_palavra_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizadoraula',
            name='aula',
        ),
        migrations.AlterField(
            model_name='palavra',
            name='aula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aulas.aula'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='utilizadoraula',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='utilizadoraula',
            name='utilizador',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='palavra',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='palavra',
            name='nome',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(default='Sem descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(default='Sem descrição', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palavra',
            name='categoria',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='palavra',
            name='palavra',
            field=models.CharField(default='palavra-padrão', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.DeleteModel(
            name='UtilizadorAula',
        ),
    ]
