# Generated by Django 5.1.7 on 2025-05-04 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa', '0005_remove_utilizadoraula_aula_alter_palavra_aula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palavra',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pesquisa.categoria'),
        ),
    ]
