# Generated by Django 5.1.7 on 2025-04-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilizador',
            name='idade',
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
