# Generated by Django 5.1.7 on 2025-04-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizador', '0002_remove_utilizador_idade_alter_utilizador_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
