# Generated by Django 5.1.7 on 2025-04-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='texto',
        ),
        migrations.AddField(
            model_name='resposta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='respostas/'),
        ),
    ]
