# Generated by Django 5.1.7 on 2025-04-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0004_alter_resposta_imagem_alter_resposta_pergunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='explicacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
