# Generated by Django 5.1.7 on 2025-04-22 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0006_remove_resposta_explicacao_remove_resposta_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='explicacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='texto',
            field=models.TextField(default='Sem texto'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='imagem',
            field=models.ImageField(blank=True, default='path/to/default/image.png', null=True, upload_to='respostas/'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='testes.pergunta'),
        ),
    ]
