# Generated by Django 5.1.7 on 2025-04-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0007_resposta_explicacao_resposta_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='tempo',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='tentativas',
            field=models.IntegerField(default=1),
        ),
    ]
