# Generated by Django 5.1.7 on 2025-04-29 10:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0008_aula_numero'),
        ('testes', '0011_remove_teste_estado_resultadopergunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='mensagem_inicial',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='perguntas_respondidas',
        ),
        migrations.RemoveField(
            model_name='teste',
            name='total_perguntas',
        ),
        migrations.AlterField(
            model_name='resposta',
            name='imagem',
            field=models.ImageField(default='respostas/aula-a.png', upload_to='respostas/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.pergunta'),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='pontuacao',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='tempo',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='tentativas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teste',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.aula'),
        ),
        migrations.AlterField(
            model_name='teste',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ResultadoPergunta',
        ),
    ]
