# Generated by Django 5.1.7 on 2025-05-09 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0015_teste_mensagem_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correta', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.pergunta')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.resposta')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.resultado')),
            ],
        ),
    ]
