# Generated by Django 5.1.7 on 2025-05-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0016_tentativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='numero',
            field=models.PositiveIntegerField(default=1, help_text='Número da pergunta no teste'),
            preserve_default=False,
        ),
    ]
