# Generated by Django 5.1.7 on 2025-05-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0017_pergunta_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='numero',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
