# Generated by Django 5.1.7 on 2025-05-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0018_alter_pergunta_numero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tentativa',
        ),
    ]
