# Generated by Django 5.1.7 on 2025-05-12 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0018_alter_pergunta_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tentativa',
            old_name='correta',
            new_name='acertou',
        ),
        migrations.RenameField(
            model_name='tentativa',
            old_name='timestamp',
            new_name='data',
        ),
        migrations.AlterUniqueTogether(
            name='tentativa',
            unique_together={('utilizador', 'pergunta', 'teste')},
        ),
        migrations.AddField(
            model_name='tentativa',
            name='tentativas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tentativa',
            name='teste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testes.teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tentativa',
            name='utilizador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='resposta',
        ),
        migrations.RemoveField(
            model_name='tentativa',
            name='resultado',
        ),
    ]
