# Generated by Django 5.1.7 on 2025-05-12 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0019_delete_tentativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('acertou', models.BooleanField(default=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.pergunta')),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.teste')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizador', 'pergunta', 'teste')},
            },
        ),
    ]
